trigger:
  branches:
    include:
    - '*'

pool:
  name: TBS Linux Self Hosted

steps:
- script: |
    echo Sync azure repo
    B64_PAT=$(echo -n ":$PAT" | base64)
    git clone --bare https://$PAT@dev.azure.com/tbs-sct/GCExchange/_git/$REPO_NAME Sync_director
    cd Sync_directory
    git remote add --mirror=fetch upstream https://github.com/gcxchange-gcechange/$REPO_NAME
    git fetch upstream --tags
    git push https://$PAT@dev.azure.com/tbs-sct/GCExchange/_git/$REPO_NAME --all
  env:
    PAT: $(PAT)
    REPO_NAME: "appsvc-function-dev-cm-stats-dotnet001"
  displayName: 'Sync repo'
